name: MSE5-AutoApi

on:
  schedule:
    - cron: 12 */6 * * 1-5 # 每周1-5每6小时执行一次
  # 手动执行
  workflow_dispatch:
  # watch:
  #   types: [started]

jobs:
  build:
    runs-on: ubuntu-latest
    # if: github.event.repository.owner.id == github.event.sender.id # self started
    steps:
      - uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: run api
        run: |
          python microsoft_e5.py
        env:
          MS_TOKEN: ${{ secrets.MS_TOKEN }}
          MS_CLIENT_ID: ${{ secrets.MS_CLIENT_ID }}
          MS_CLIENT_SECRET: ${{ secrets.MS_CLIENT_SECRET }}
          # wechat app id
          WX_CORP_ID: ${{ secrets.WX_CORP_ID }}
          WX_APP_ID: ${{ secrets.WX_APP_ID }}
          WX_APP_SECRET: ${{ secrets.WX_APP_SECRET }}
